# Generated by Django 5.2.8 on 2025-11-14 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=70)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=100)),
                ('plec', models.IntegerField(choices=[(1, 'Kobieta'), (2, 'Mezczyzna'), (3, 'Inna')], default=3)),
                ('data_dodania', models.DateField(auto_now_add=True)),
                ('stanowsiko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.stanowisko')),
            ],
        ),
    ]
