# Generated by Django 5.2.7 on 2025-12-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0002_stanowisko_osoba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osoba',
            old_name='stanowsiko',
            new_name='stanowisko',
        ),
    ]
